package:
  name: tensorflow
  version: "0.9.0"

source:
  fn: v0.9.0.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v0.9.0.tar.gz
  sha256: 3128c396af19518c642d3e590212291e1d93c5b047472a10cf3245b53adac9c9

build:
  number: 0
  skip: True  # [win]
  skip: True  # [py26]
  skip: True  # [py33]
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    - python
    - pip
    - swig
    - numpy >=1.10.1
    - protobuf ==3.0.0b2
    - six >=1.10.0
    - wheel
    - zlib
    # bazel is also a build requirement but is being provided by the system
  run:
    - python
    - numpy >=1.10.1
    - protobuf ==3.0.0b2
    - six >=1.10.0

test:
  imports:
    - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

extra:
  recipe-maintainers:
    - jjhelmus
